version: '3'

services:
  # Database container for PostgreSQL
  db:
    image: postgres:bullseye
    container_name: 'db'
    env_file:
        - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # PGAdmin container for PostgreSQL
  pgadmin:
      image: dpage/pgadmin4
      container_name: 'pgadmin'
      env_file:
        - .env
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
      - "5050:80"
      networks:
      - app-network
      volumes:
        - pgadmin_data:/var/lib/pgadmin/

  # Linux container for the application and its dependencies
#  app:
#      build:
#        context: .
#        dockerfile: Dockerfile
#      container_name: 'app'
#      env_file:
#      - .env
#      ports:
#      - "8000:8000"
#      networks:
#      - app-network
#      volumes:
#        - app_data:/app

volumes:
  postgres_data:
  pgadmin_data:
  app_data:

networks:
  app-network:
    driver: bridge